version: '3.7'

services:
  api:
    build: .
    container_name: api-hotel
    command: npm run start
    depends_on:
      - mysqldb
    expose:
      - 5000
    ports: 
      - 5000:5000
    volumes:
      - .:/usr/src/app

  mysqldb:
    container_name: db-node-mysql
    env_file: ./.env
    environment:
      MYSQL_PASSWORD: ${DATABASE_PASS}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASS}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_TCP_PORT: 3307
    image: mysql:5.6
    command: mysqld --default_authentication_plugin=mysql_native_password
    ports:
      - 3307:3307
    expose:
      - 3307
    restart: always
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql
      - ./db/backup/files/:/data_backup/

volumes: 
  db-config:
  db-data: